name: Run Name Script

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace ubuntu:latest /bin/bash -c "apt update && apt install -yqq curl && bash script.sh"
